### ISSUE TITLE
Class is not autoloadable

### ISSUE THREAD

**Issue by henryruhs** [slowprog/CopyFile#6]
Hello,

I found an issue while using:

```
composer install --no-dev
```

That is causing:

```
Class SlowProg\CopyFile\ScriptHandler is not autoloadable, can not call post-install-cmd script
```

**Comment by slowprog** [comment]
Sorry for late. I was a little busy =)

I can not find a bug. If it is still relevant, can you show your composer.json?

**Comment by henryruhs** [comment]
Yes, this still happens on my project:

```
git clone https://github.com/redaxscript/redaxscript
```

**Comment by slowprog** [comment]
Yep, I got it. You have following *composer.json*:

```
"require-dev":
{
    ...
    "fbourigault/composer-mkdir": "2.0.0",
    ...
    "slowprog/composer-copy-file": "0.2.0",
    ...
},
"scripts":
{
    "post-install-cmd":
    [
        "SlowProg\\CopyFile\\ScriptHandler::copy",
        "Fbourigault\\ComposerMkdir\\ScriptHandler::mkdirs"
    ],
    ...
},
```

When you run `composer install --no-dev`, composer try call *ScriptHandler::copy()*, but it's no exists, because flag --no-dev forbids uploading deps from require-dev. 

You have three ways:

1. Not run scripts when --no-dev: `composer install --no-dev --no-scripts`.

2. Move deps *fbourigault/composer-mkdir* and *slowprog/composer-copy-file* to require block.

3. Use composer-plugin [scriptsdev](https://github.com/neronmoon/scriptsdev).

**Comment by henryruhs** [comment]
Thank you for pointing it out, I will give scriptsdev a try. Have a nice day!
